// Plain ESM, no deps: reads ../services.json and writes one systemd --user unit per
// monitored service, plus marketplace.target and marketplace-status.service, into
// systemd/units/ (override with --out). Pure function of services.json — same input,
// byte-identical output — so re-running after an unrelated edit elsewhere is a no-op.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Anchor every path off this file's own location, not process.cwd(), so
// `node systemd/generate.mjs` behaves the same run from anywhere.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const systemdDir = __dirname;
const serviceStatusDir = path.resolve(systemdDir, '..');
const defaultOutDir = path.join(systemdDir, 'units');

const GENERATED_BANNER =
  '# GENERATED by marketplace-services-status/systemd/generate.mjs — do not edit by hand.';

function parseArgs(argv) {
  let outDir = defaultOutDir;
  // Stryker disable next-line EqualityOperator: `i <= argv.length` only adds one extra pass with
  // i === argv.length. On any real array (this one is process.argv.slice(2), or a plain array in
  // tests) argv[argv.length] is always undefined by definition, and undefined can never equal the
  // string '--out', so that extra pass can never enter the body's branch — it is inert on every
  // reachable argv, not just the ones exercised here.
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--out') {
      const value = argv[i + 1];
      if (!value) {
        throw new Error('--out requires a directory argument');
      }
      outDir = path.resolve(value);
      i++;
    }
  }
  return { outDir };
}

// services.json spells nvmDir as "~/.nvm" for a human reading the file; systemd never
// expands '~', so expand it against the real home directory before it lands in a unit.
function expandHome(p) {
  if (p === '~') return os.homedir();
  if (p.startsWith('~/')) return path.join(os.homedir(), p.slice(2));
  return p;
}

function loadConfig() {
  const raw = readFileSync(path.join(serviceStatusDir, 'services.json'), 'utf8');
  return JSON.parse(raw);
}

function flattenServices(config) {
  const flat = [];
  for (const group of config.groups) {
    for (const service of group.services) {
      flat.push({ ...service, groupId: group.id, groupTitle: group.title });
    }
  }
  return flat;
}

// Build the ExecStart command for a repo, and this is the one place worth reading twice.
//
// The obvious spelling is `ExecStart=<yarn> dev`. It is wrong here, measured rather than
// assumed: yarn 1.x sits between systemd and the real process, and under KillMode=control-group
// it sees its child die under the same SIGTERM and exits 1 — so an ordinary `systemctl stop`
// records Result=exit-code and the unit lands in 'failed', which is the exact state a *crash*
// is supposed to produce. The whole point of Restart=no here is that the page can tell a
// crashed dev server from a stopped one, and yarn in the middle destroys that distinction.
// KillMode=mixed does not rescue it either: yarn still exits 1 and its children are orphaned
// instead (verified — two vite processes survived the stop).
//
// So: read the repo's own package.json script, split the `&&` chain, and `exec` the final
// segment under /bin/sh. `exec` is the load-bearing word — it replaces the shell, so the real
// process (vite / tsx) becomes the unit's MainPID and receives SIGTERM directly, exiting 0.
// Earlier segments (`tsc`) stay ahead of it and still fail the unit loudly if they fail.
// package.json stays the source of truth; nothing about the command is restated here.
//
// Bare binaries resolve against the repo's node_modules/.bin because the unit's PATH carries
// the pinned node and nothing repo-local. A leading `npx ` is dropped: npx would re-resolve
// the very binary we just resolved, and add another process between systemd and the target.
function buildExecCommand({ repoAbs, service }) {
  const pkgPath = path.join(repoAbs, 'package.json');
  let script;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    // Stryker disable next-line OptionalChaining: dropping `?.` only changes what happens when
    // pkg.scripts is nullish — `pkg.scripts[...]` throws instead of `pkg.scripts?.[...]` short-
    // circuiting to undefined. Both land in the same place: the throw is caught below and `script`
    // keeps the `undefined` it was declared with, the exact value the optional-chaining form would
    // have produced directly. No reachable pkg.scripts value makes the two diverge.
    script = pkg.scripts?.[service.script];
  } catch {
    // ⚠️ Deliberately empty, and it has to stay that way. This only runs when the try block threw
    // before reaching the assignment above (readFileSync/JSON.parse failing, or — see the
    // OptionalChaining note — a nullish pkg.scripts), so `script` still holds the `undefined` of its
    // own declaration and there is nothing here to reset. The `script = undefined;` that used to sit
    // here was not merely redundant: no test could observe it, so no test could kill the mutant that
    // deleted it, and it held the mutation gate at 99.95 by itself. An empty block Stryker does not
    // mutate at all.
  }
  if (!script) {
    throw new Error(
      `${service.id}: no "${service.script}" script in ${pkgPath}. ` +
        'services.json names a script that repo does not define.'
    );
  }
  // Mask the one operator we do handle before looking for the ones we do not — testing for a
  // lone '&' against the raw string matches the second '&' of every '&&' and rejects everything.
  // Stryker disable next-line StringLiteral: withoutChain is read only by the character-class
  // test below, which asks "is any of ;|&$`(){}<> present anywhere", not "what replaced '&&'" —
  // adjacency and replacement length are invisible to it. '\u0000' and '' both remove every '&'
  // that was part of a '&&' pair and introduce none of the flagged characters, so for any script
  // string the two replacements make that test return the same boolean.
  const withoutChain = script.replace(/&&/g, '\u0000');
  if (/[;|&$`(){}<>]/.test(withoutChain)) {
    throw new Error(
      `${service.id}: the "${service.script}" script uses shell syntax this generator does not ` +
        `parse (${JSON.stringify(script)}). Simplify the script, or teach buildExecCommand about it — ` +
        'guessing here would silently produce a unit that runs the wrong thing.'
    );
  }
  const segments = script
    .split('&&')
    .map((s) => s.trim())
    .filter(Boolean);
  const resolved = segments.map((segment) => {
    const parts = segment.split(/\s+/);
    if (parts[0] === 'npx') parts.shift();
    const localBin = path.join(repoAbs, 'node_modules', '.bin', parts[0]);
    if (existsSync(localBin)) parts[0] = localBin;
    return parts.join(' ');
  });
  const last = resolved.pop();
  const chain = [...resolved, `exec ${last}`].join(' && ');
  return { shellCommand: chain, sourceScript: script };
}

function serviceUnitContent({ service, workspaceRootAbs, nodeBinDir, unitTarget }) {
  const unit = `${service.id}.service`;
  const repoAbs = path.join(workspaceRootAbs, service.repo);
  const { shellCommand, sourceScript } = buildExecCommand({ repoAbs, service });
  const lines = [
    GENERATED_BANNER,
    '# No [Install] section: `systemctl --user enable` refuses on a unit with no [Install] —',
    "# the unit shows as 'static', which is what makes \"never start at boot\" structural rather",
    '# than a convention someone has to remember to follow.',
    '[Unit]',
    `Description=${service.label} (${service.groupTitle}) — ${service.description}`,
    `Documentation=file://${repoAbs}`,
    `PartOf=${unitTarget}`,
    // No After=network-online.target: `systemctl --user show network-online.target
    // -p LoadState` reports `not-found` in the --user manager (verified on this
    // host), and there is no standard --user-scope equivalent to substitute. These
    // are local dev servers binding local ports — nothing here waits on DNS or a
    // remote mount — so omitting a network gate is correct, not a shortcut.
    '',
    '[Service]',
    'Type=simple',
    `WorkingDirectory=${repoAbs}`,
    // Pinned nvm bin dir first: the node_modules/.bin shims below are `#!/usr/bin/env node`,
    // so this is what decides which node they run under. The machine default is a different
    // minor (24.14 vs the 24.18 in services.json), and every repo's engines is ^24.18.0.
    `Environment=PATH=${nodeBinDir}:/usr/local/bin:/usr/bin:/bin`,
    'Environment=NODE_ENV=development',
    `# from ${service.repo}/package.json scripts.${service.script}: ${sourceScript}`,
    `ExecStart=/bin/sh -c '${shellCommand}'`,
    "# Restart=no: a crashed dev server must stay 'failed' so the status page shows it broken;",
    '# an auto-restart loop would hide the error and spam the journal instead.',
    'Restart=no',
    // control-group, not mixed: vite spawns rolldown workers and tsx spawns a watcher, and
    // under mixed only MainPID is signalled — measured, three vite processes outlived the stop.
    'KillMode=control-group',
    'KillSignal=SIGTERM',
    // The pairing that makes the page honest. These dev servers do not install a SIGTERM
    // handler consistently, and the three spellings below are all measured, not defensive:
    // vite exits with code 143, `tsx watch` exits with code 15, and a plain node with no
    // handler is *killed by* the signal (Result=signal, not exit-code). Miss any one and that
    // family of services goes 'failed' on every ordinary stop —
    // which without this line is Result=exit-code, i.e. 'failed', i.e. identical to a crash.
    // Declaring SIGTERM successful marks the *stop* path clean while leaving every real
    // failure (tsc error, EADDRINUSE, uncaught throw — all ordinary non-zero exits) still
    // 'failed'. That is the distinction Restart=no exists to preserve; SuccessExitStatus=1
    // would have bought the same green stop by throwing the distinction away.
    'SuccessExitStatus=143 15 SIGTERM',
    'TimeoutStopSec=20',
    `SyslogIdentifier=${service.id}`,
    'StandardOutput=journal',
    'StandardError=journal',
    ''
  ];
  return { unit, content: lines.join('\n') };
}

function targetUnitContent({ services, unitTarget }) {
  const units = services.map((s) => `${s.id}.service`);
  const lines = [
    GENERATED_BANNER,
    '# No [Install] section, matching every unit it groups: the target itself must not be',
    '# enable-able at boot either — "start only from the control page" holds platform-wide.',
    '[Unit]',
    `Description=Marketplace platform — all ${units.length} monitored dev services`,
    // Wants= starts them together; each unit's own PartOf=<this target> is what makes a
    // stop/restart of the target propagate back down (Wants= alone would not).
    ...units.map((u) => `Wants=${u}`),
    ...units.map((u) => `After=${u}`),
    ''
  ];
  return { unit: unitTarget, content: lines.join('\n') };
}

function monitorUnitContent({ config, nodeBinDir }) {
  // Same exec treatment as the monitored units, for the same reason — this also has to be
  // stoppable without landing in 'failed'. Its own package.json is the source of the command.
  const { shellCommand, sourceScript } = buildExecCommand({
    repoAbs: serviceStatusDir,
    service: { id: 'marketplace-status', script: 'start' }
  });
  const lines = [
    GENERATED_BANNER,
    '# The ONE generated unit that carries [Install]: the control page has to be reachable',
    '# to start anything else, so it alone may be enabled at boot. install.sh installs this',
    '# file but does not enable it — enabling is a separate, explicit step (see README.md),',
    '# and enabling it does not enable any unit it monitors (those still have no [Install]).',
    '[Unit]',
    'Description=Marketplace services status monitor — the control page itself',
    `Documentation=file://${serviceStatusDir}`,
    // See the comment in serviceUnitContent(): network-online.target does not
    // exist in the --user manager and this is a local dev server too, so it
    // gets no network gate either.
    '',
    '[Service]',
    'Type=simple',
    `WorkingDirectory=${serviceStatusDir}`,
    `Environment=PATH=${nodeBinDir}:/usr/local/bin:/usr/bin:/bin`,
    'Environment=NODE_ENV=production',
    `# from marketplace-services-status/package.json scripts.start: ${sourceScript}`,
    `ExecStart=/bin/sh -c '${shellCommand}'`,
    "# Restart=on-failure, unlike the monitored units: this IS the control plane — nothing",
    '# else can restart it if it dies, so (unlike a crashed dev server, which must stay',
    "# 'failed' for the page to show it) it should recover on its own.",
    'Restart=on-failure',
    'RestartSec=2',
    // Matches the monitored units: see the long comment in serviceUnitContent().
    'KillMode=control-group',
    'KillSignal=SIGTERM',
    'SuccessExitStatus=143 15 SIGTERM',
    'TimeoutStopSec=20',
    'SyslogIdentifier=marketplace-status',
    'StandardOutput=journal',
    'StandardError=journal',
    '',
    '[Install]',
    'WantedBy=default.target',
    ''
  ];
  return { unit: config.monitorUnit, content: lines.join('\n') };
}

function main() {
  const { outDir } = parseArgs(process.argv.slice(2));
  const config = loadConfig();
  const services = flattenServices(config);

  // services.json's own header says the two consumers of this file must never disagree on
  // workspaceRoot — config.ts honors a WORKSPACE_ROOT override (for a relocated checkout, or a
  // test), so this generator has to resolve it the same way rather than always falling back to the
  // path baked into services.json.
  const workspaceRootOverride = process.env.WORKSPACE_ROOT;
  const workspaceRootAbs = workspaceRootOverride
    ? path.resolve(workspaceRootOverride)
    : path.resolve(serviceStatusDir, config.workspaceRoot);
  const nvmDirAbs = expandHome(config.nvmDir);
  // The nvm bin dir for the pinned version. Units no longer invoke yarn at all, but this still
  // has to lead the unit PATH: the node_modules/.bin shims are `#!/usr/bin/env node` scripts,
  // so whichever node this dir puts first is the one every service actually runs under.
  const nodeBinDir = path.join(nvmDirAbs, 'versions', 'node', `v${config.nodeVersion}`, 'bin');

  mkdirSync(outDir, { recursive: true });

  const files = [];
  for (const service of services) {
    files.push(serviceUnitContent({ service, workspaceRootAbs, nodeBinDir, unitTarget: config.unitTarget }));
  }
  files.push(targetUnitContent({ services, unitTarget: config.unitTarget }));
  files.push(monitorUnitContent({ config, nodeBinDir }));

  for (const { unit, content } of files) {
    writeFileSync(path.join(outDir, unit), content, 'utf8');
  }

  console.log(`Wrote ${files.length} unit files to ${outDir}`);
}

main();
