#!/usr/bin/env bash
# Removes the units install.sh installed, and only those. The candidate name list
# comes from install.sh's manifest when one is present (what it actually installed
# last time), falling back to the services.json-derived list otherwise — but naming
# a file is not what makes removal safe: names like marketplace-admin.service or
# marketplace.target are generic enough that an unrelated pre-existing user unit
# could share one, so every candidate is also grepped for generate.mjs's banner
# before rm -f, and anything without it is skipped rather than deleted.
set -euo pipefail

if [ "${EUID:-$(id -u)}" -eq 0 ]; then
  echo "Refusing to run as root — these are systemd --user units." >&2
  exit 1
fi

DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *)
      echo "Unknown argument: $arg (only --dry-run is supported)" >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_STATUS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
USER_UNIT_DIR="$HOME/.config/systemd/user"
# Written by install.sh: the exact set of filenames it generated last time, so a
# service renamed/removed from services.json since then is still found and
# removed here even though re-deriving the list from the CURRENT services.json
# would no longer mention it.
MANIFEST_PATH="$USER_UNIT_DIR/.marketplace-status-manifest"
export SERVICE_STATUS_DIR

read -r UNIT_TARGET MONITOR_UNIT < <(
  node -e '
    const fs = require("node:fs");
    const path = require("node:path");
    const dir = process.env.SERVICE_STATUS_DIR;
    const cfg = JSON.parse(fs.readFileSync(path.join(dir, "services.json"), "utf8"));
    // Trailing newline is load-bearing: `read` returns 1 at EOF with no delimiter,
    // which trips `set -e` and kills the script before the first echo even though
    // every variable was assigned correctly.
    process.stdout.write([cfg.unitTarget, cfg.monitorUnit].join(" ") + "\n");
  '
)

echo "== marketplace-services-status: systemd uninstall =="
echo ""

if [ -f "$MANIFEST_PATH" ]; then
  UNIT_NAMES="$(cat "$MANIFEST_PATH")"
  echo "[ok] using installed-unit manifest: $MANIFEST_PATH"
else
  # No manifest (e.g. units installed by an older version of install.sh, or the
  # manifest was removed by hand) — fall back to deriving the list from the
  # CURRENT services.json, same as before this file tracked a manifest. This
  # cannot see a since-renamed/removed service; that gap is exactly why
  # install.sh now writes the manifest in the first place.
  echo "[ok] no manifest at $MANIFEST_PATH — falling back to services.json-derived list"
  UNIT_NAMES="$(
    node -e '
      const fs = require("node:fs");
      const path = require("node:path");
      const dir = process.env.SERVICE_STATUS_DIR;
      const cfg = JSON.parse(fs.readFileSync(path.join(dir, "services.json"), "utf8"));
      const names = [];
      for (const g of cfg.groups) for (const s of g.services) names.push(s.id + ".service");
      names.push(cfg.unitTarget);
      names.push(cfg.monitorUnit);
      process.stdout.write(names.join("\n"));
    '
  )"
fi
echo ""

# Stop the target first — PartOf=marketplace.target on every monitored unit
# propagates the stop — then the monitor itself, which has no PartOf= of its own.
if $DRY_RUN; then
  echo "[dry-run] would run: systemctl --user stop $UNIT_TARGET $MONITOR_UNIT"
else
  systemctl --user stop "$UNIT_TARGET" "$MONITOR_UNIT" 2>/dev/null || true
  echo "[ok] stopped $UNIT_TARGET and $MONITOR_UNIT (if they were running)"
fi

REMOVED=0
SKIPPED=0
while IFS= read -r name; do
  [ -z "$name" ] && continue
  target="$USER_UNIT_DIR/$name"
  if [ -f "$target" ]; then
    # Provenance check: a filename match alone is not proof this file is ours —
    # marketplace-admin.service, marketplace.target etc. are generic enough that
    # a pre-existing unrelated user unit could carry the same name. Only ever
    # remove a file that carries generate.mjs's own banner.
    if ! grep -q '^# GENERATED by marketplace-services-status/systemd/generate.mjs' "$target"; then
      echo "!! SKIPPED $target — present but has no generate.mjs banner (not ours, left in place)" >&2
      SKIPPED=$((SKIPPED + 1))
      continue
    fi
    if $DRY_RUN; then
      echo "[dry-run] would remove $target"
    else
      rm -f "$target"
      echo "[ok] removed $target"
    fi
    REMOVED=$((REMOVED + 1))
  fi
done <<<"$UNIT_NAMES"

if [ "$REMOVED" -eq 0 ] && [ "$SKIPPED" -eq 0 ]; then
  echo "Nothing to remove — no generated unit was present in $USER_UNIT_DIR."
fi

# The manifest is install.sh's own bookkeeping, not a unit — drop it too so a
# future install starts clean rather than diffing against a stale record.
if [ -f "$MANIFEST_PATH" ]; then
  if $DRY_RUN; then
    echo "[dry-run] would remove manifest $MANIFEST_PATH"
  else
    rm -f "$MANIFEST_PATH"
    echo "[ok] removed manifest $MANIFEST_PATH"
  fi
fi

if $DRY_RUN; then
  echo "[dry-run] would run: systemctl --user daemon-reload"
else
  systemctl --user daemon-reload
  echo "[ok] daemon-reload done"
fi

echo ""
echo "Done. $REMOVED unit(s) removed, $SKIPPED left alone (present but not ours)."
echo "Only units carrying the generate.mjs banner were touched; anything else"
echo "already present in $USER_UNIT_DIR was left alone."
