/**
 * `systemd/generate.mjs` — `yarn systemd:generate`, and the one JavaScript file in this repo
 * outside `src/`.
 *
 * It is a script, not a module: no exports, three hundred lines of top-level `main()`. So the only
 * way to exercise it is to import it for its side effects, once per case, with the filesystem and
 * `process.argv` replaced — which is what `boot()` below does. What it *is*, though, is the thing
 * that decides what `systemctl --user start` actually runs for thirteen units, so every line it
 * writes into a unit file is a claim worth asserting.
 *
 * ⚠️ **`node:fs` is mocked rather than pointed at a temp tree.** The generator resolves the repos
 * it reads out of `services.json`'s `workspaceRoot`, so a real-filesystem test would read the
 * fifteen sibling repos' own `package.json` files and go red when one of them edited a script it
 * has nothing to do with. The fixtures here are the shapes, and the real `services.json` is
 * checked by `test/config.test.ts` against the same file the monitor reads.
 *
 * ⚠️ **`vi.resetModules()` before every import is what makes the cases independent.** A module is
 * evaluated once per registry, so without it the second `import()` returns the first case's cached
 * module, writes nothing, and asserts nothing at all — while passing.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const fs = vi.hoisted(() => ({
  existsSync: vi.fn(),
  mkdirSync: vi.fn(),
  readFileSync: vi.fn(),
  writeFileSync: vi.fn()
}));

const os = vi.hoisted(() => ({ homedir: vi.fn() }));

vi.mock('node:fs', () => fs);
vi.mock('node:os', () => ({ default: os }));

// The three directories the generator derives from its own location, derived here the same way and
// from this file's own location — a literal would be a second copy of the layout to keep in step.
const systemdDir = fileURLToPath(new URL('../systemd', import.meta.url));
const repoDir = path.resolve(systemdDir, '..');
const workspaceRoot = path.resolve(repoDir, '..');
const defaultOutDir = path.join(systemdDir, 'units');

const BANNER =
  '# GENERATED by marketplace-services-status/systemd/generate.mjs — do not edit by hand.';

/** Where a monitored repo's `node_modules/.bin` entry would be, for the `existsSync` fixture. */
const repoBin = (repo: string, name: string): string =>
  path.join(workspaceRoot, repo, 'node_modules', '.bin', name);

/** The same, for this repo — the monitor unit resolves its own command against its own bin dir. */
const ownBin = (name: string): string => path.join(repoDir, 'node_modules', '.bin', name);

const service = (patch: Record<string, unknown> = {}): Record<string, unknown> => ({
  id: 'api',
  label: 'API',
  repo: 'BEs/dev/api',
  kind: 'backend',
  script: 'dev',
  port: 4027,
  path: '/api',
  description: 'The API service',
  ...patch
});

const config = (patch: Record<string, unknown> = {}): Record<string, unknown> => ({
  workspaceRoot: '..',
  nodeVersion: '24.18.0',
  nvmDir: '~/.nvm',
  unitTarget: 'marketplace.target',
  monitorUnit: 'marketplace-status.service',
  groups: [{ id: 'core', title: 'Core', description: 'The core tier', services: [service()] }],
  ...patch
});

const DEFAULT_PACKAGES: Record<string, unknown> = { 'BEs/dev/api': { scripts: { dev: 'vite' } } };
const DEFAULT_MONITOR = { scripts: { start: 'node dist/server.js' } };

interface BootOptions {
  config?: Record<string, unknown>;
  packages?: Record<string, unknown>;
  monitor?: unknown;
  bins?: string[];
  argv?: string[];
  /**
   * Overrides `process.argv` outright instead of appending `argv` after the usual
   * `['/usr/bin/node', '.../generate.mjs']` prefix — for the one test that has to control what
   * lands at index 0 and 1, where the normal helper never would.
   */
  rawArgv?: string[];
}

const realArgv = process.argv;

let log: ReturnType<typeof vi.spyOn>;

beforeEach(() => {
  fs.existsSync.mockReset();
  fs.mkdirSync.mockReset();
  fs.readFileSync.mockReset();
  fs.writeFileSync.mockReset();
  os.homedir.mockReturnValue('/home/tester');
  log = vi.spyOn(console, 'log').mockImplementation(() => undefined);
});

afterEach(() => {
  process.argv = realArgv;
  vi.restoreAllMocks();
});

/** Run the generator once against a fixture filesystem and a fixture command line. */
const boot = async ({
  config: cfg = config(),
  packages = DEFAULT_PACKAGES,
  monitor = DEFAULT_MONITOR,
  bins = [],
  argv = [],
  rawArgv
}: BootOptions = {}): Promise<void> => {
  const files = new Map<string, string>();

  files.set(path.join(repoDir, 'services.json'), JSON.stringify(cfg));
  files.set(path.join(repoDir, 'package.json'), JSON.stringify(monitor));
  for (const [repo, pkg] of Object.entries(packages)) {
    files.set(
      path.join(workspaceRoot, repo, 'package.json'),
      typeof pkg === 'string' ? pkg : JSON.stringify(pkg)
    );
  }

  fs.readFileSync.mockImplementation((p: unknown) => {
    const found = files.get(String(p));

    if (found === undefined) {
      throw new Error(`ENOENT: no such file or directory, open '${String(p)}'`);
    }

    return found;
  });
  fs.existsSync.mockImplementation((p: unknown) => bins.includes(String(p)));

  process.argv = rawArgv ?? ['/usr/bin/node', path.join(systemdDir, 'generate.mjs'), ...argv];

  vi.resetModules();
  await import('../systemd/generate.mjs');
};

/** Every file the run wrote, by absolute path. */
const written = (): Map<string, string> =>
  new Map(fs.writeFileSync.mock.calls.map((call) => [String(call[0]), String(call[1])]));

/** One written unit by name, or a failure that says which — never an undefined dereference. */
const unit = (name: string, outDir: string = defaultOutDir): string => {
  const found = written().get(path.join(outDir, name));

  if (found === undefined) {
    throw new Error(`nothing was written to ${path.join(outDir, name)}`);
  }

  return found;
};

/** The single line of a unit starting with `prefix`, for the assertions that are about one line. */
const line = (content: string, prefix: string): string => {
  const found = content.split('\n').filter((l) => l.startsWith(prefix));

  if (found.length !== 1) {
    throw new Error(`expected exactly one ${prefix}… line, found ${found.length}`);
  }

  return found[0];
};

const TWO_GROUPS = config({
  groups: [
    {
      id: 'core',
      title: 'Core',
      description: 'The core tier',
      services: [service(), service({ id: 'web', label: 'Web', repo: 'FEs/web', script: 'dev' })]
    },
    {
      id: 'edge',
      title: 'Edge',
      description: 'The edge tier',
      services: [service({ id: 'gw', label: 'Gateway', repo: 'BEs/dev/gw', script: 'serve' })]
    }
  ]
});

const TWO_GROUPS_PACKAGES: Record<string, unknown> = {
  'BEs/dev/api': { scripts: { dev: 'vite' } },
  'FEs/web': { scripts: { dev: 'vite' } },
  'BEs/dev/gw': { scripts: { serve: 'tsx watch src/index.ts' } }
};

describe('the unit generator', () => {
  it('writes one unit per service across every group, plus the target and the monitor', async () => {
    await boot({ config: TWO_GROUPS, packages: TWO_GROUPS_PACKAGES });

    expect(fs.mkdirSync).toHaveBeenCalledWith(defaultOutDir, { recursive: true });
    expect([...written().keys()]).toStrictEqual([
      path.join(defaultOutDir, 'api.service'),
      path.join(defaultOutDir, 'web.service'),
      path.join(defaultOutDir, 'gw.service'),
      path.join(defaultOutDir, 'marketplace.target'),
      path.join(defaultOutDir, 'marketplace-status.service')
    ]);
    expect(log).toHaveBeenCalledWith(`Wrote 5 unit files to ${defaultOutDir}`);
  });

  it('writes to --out instead, resolved against the working directory', async () => {
    const outDir = path.resolve('build/units');

    await boot({ argv: ['--out', 'build/units'] });

    expect(fs.mkdirSync).toHaveBeenCalledWith(outDir, { recursive: true });
    expect(unit('api.service', outDir)).toContain(BANNER);
    expect(written().has(path.join(defaultOutDir, 'api.service'))).toBe(false);
  });

  it('ignores an argument it does not know', async () => {
    await boot({ argv: ['--verbose'] });

    expect(fs.mkdirSync).toHaveBeenCalledWith(defaultOutDir, { recursive: true });
  });

  // main() must hand parseArgs() only the caller-supplied arguments — process.argv[0] and [1]
  // are always the node binary and this script's own path, never something a user typed. Proven
  // here with a two-element process.argv standing in for exactly that pair: if main() forgot to
  // slice them off, this '--out' would be seen as index 0 of the args and 'nonsense' taken as its
  // value, moving outDir away from the default.
  it('never mistakes the interpreter path or this script path for a --out flag', async () => {
    await boot({ rawArgv: ['--out', 'nonsense'] });

    expect(fs.mkdirSync).toHaveBeenCalledWith(defaultOutDir, { recursive: true });
  });

  // Falling back to the default output directory here would write thirteen units somewhere the
  // caller did not ask for, which `install.sh` would then install.
  it('refuses --out with nothing after it rather than falling back to the default', async () => {
    await expect(boot({ argv: ['--out'] })).rejects.toThrow('--out requires a directory argument');

    expect(fs.mkdirSync).not.toHaveBeenCalled();
    expect(fs.writeFileSync).not.toHaveBeenCalled();
  });
});

// Every read and write here goes through Buffer<->string once, at a boundary humans then read
// (a unit file, a diagnostic in a thrown Error). Dropping the encoding argument would still run —
// readFileSync/writeFileSync default to a Buffer/binary — so only the exact call arguments prove
// 'utf8' is actually there, not just that some content came back.
describe('the encoding every read and write asks for', () => {
  it('reads services.json and a monitored repo package.json as utf8, not binary', async () => {
    await boot();

    expect(fs.readFileSync).toHaveBeenCalledWith(path.join(repoDir, 'services.json'), 'utf8');
    expect(fs.readFileSync).toHaveBeenCalledWith(
      path.join(workspaceRoot, 'BEs/dev/api', 'package.json'),
      'utf8'
    );
  });

  it('writes every generated unit file as utf8, not binary', async () => {
    await boot();

    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join(defaultOutDir, 'api.service'),
      expect.any(String),
      'utf8'
    );
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join(defaultOutDir, 'marketplace.target'),
      expect.any(String),
      'utf8'
    );
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      path.join(defaultOutDir, 'marketplace-status.service'),
      expect.any(String),
      'utf8'
    );
  });
});

// These three assert the full, exact text of one unit of each kind — banner, every comment, every
// blank separator line — because `.toContain()` on a substring cannot tell a line that is still
// there from one a mutant blanked to `''`: the surrounding text it would still `.toContain()` never
// moves. Only whole-file equality notices a missing or replaced line.
describe('the exact content of a generated unit file', () => {
  it('writes the full text of a monitored service unit, comments included', async () => {
    await boot();

    const repoAbs = path.join(workspaceRoot, 'BEs/dev/api');

    expect(unit('api.service')).toBe(
      BANNER +
        '\n' +
        '# No [Install] section: `systemctl --user enable` refuses on a unit with no [Install] —\n' +
        '# the unit shows as \'static\', which is what makes "never start at boot" structural rather\n' +
        '# than a convention someone has to remember to follow.\n' +
        '[Unit]\n' +
        'Description=API (Core) — The API service\n' +
        `Documentation=file://${repoAbs}\n` +
        'PartOf=marketplace.target\n' +
        '\n' +
        '[Service]\n' +
        'Type=simple\n' +
        `WorkingDirectory=${repoAbs}\n` +
        'Environment=PATH=/home/tester/.nvm/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin\n' +
        'Environment=NODE_ENV=development\n' +
        '# from BEs/dev/api/package.json scripts.dev: vite\n' +
        "ExecStart=/bin/sh -c 'exec vite'\n" +
        "# Restart=no: a crashed dev server must stay 'failed' so the status page shows it broken;\n" +
        '# an auto-restart loop would hide the error and spam the journal instead.\n' +
        'Restart=no\n' +
        'KillMode=control-group\n' +
        'KillSignal=SIGTERM\n' +
        'SuccessExitStatus=143 15 SIGTERM\n' +
        'TimeoutStopSec=20\n' +
        'SyslogIdentifier=api\n' +
        'StandardOutput=journal\n' +
        'StandardError=journal\n'
    );
  });

  it('writes the full text of the target unit, comments included', async () => {
    await boot({ config: TWO_GROUPS, packages: TWO_GROUPS_PACKAGES });

    expect(unit('marketplace.target')).toBe(
      BANNER +
        '\n' +
        '# No [Install] section, matching every unit it groups: the target itself must not be\n' +
        '# enable-able at boot either — "start only from the control page" holds platform-wide.\n' +
        '[Unit]\n' +
        'Description=Marketplace platform — all 3 monitored dev services\n' +
        'Wants=api.service\n' +
        'Wants=web.service\n' +
        'Wants=gw.service\n' +
        'After=api.service\n' +
        'After=web.service\n' +
        'After=gw.service\n'
    );
  });

  it('writes the full text of the monitor unit, comments included', async () => {
    await boot();

    expect(unit('marketplace-status.service')).toBe(
      BANNER +
        '\n' +
        '# The ONE generated unit that carries [Install]: the control page has to be reachable\n' +
        '# to start anything else, so it alone may be enabled at boot. install.sh installs this\n' +
        '# file but does not enable it — enabling is a separate, explicit step (see README.md),\n' +
        '# and enabling it does not enable any unit it monitors (those still have no [Install]).\n' +
        '[Unit]\n' +
        'Description=Marketplace services status monitor — the control page itself\n' +
        `Documentation=file://${repoDir}\n` +
        '\n' +
        '[Service]\n' +
        'Type=simple\n' +
        `WorkingDirectory=${repoDir}\n` +
        'Environment=PATH=/home/tester/.nvm/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin\n' +
        'Environment=NODE_ENV=production\n' +
        '# from marketplace-services-status/package.json scripts.start: node dist/server.js\n' +
        "ExecStart=/bin/sh -c 'exec node dist/server.js'\n" +
        '# Restart=on-failure, unlike the monitored units: this IS the control plane — nothing\n' +
        '# else can restart it if it dies, so (unlike a crashed dev server, which must stay\n' +
        "# 'failed' for the page to show it) it should recover on its own.\n" +
        'Restart=on-failure\n' +
        'RestartSec=2\n' +
        'KillMode=control-group\n' +
        'KillSignal=SIGTERM\n' +
        'SuccessExitStatus=143 15 SIGTERM\n' +
        'TimeoutStopSec=20\n' +
        'SyslogIdentifier=marketplace-status\n' +
        'StandardOutput=journal\n' +
        'StandardError=journal\n' +
        '\n' +
        '[Install]\n' +
        'WantedBy=default.target\n'
    );
  });
});

// The unit PATH decides which node every `#!/usr/bin/env node` shim in a repo's node_modules/.bin
// runs under, so the three spellings services.json may use for the nvm directory all have to land
// as the same absolute path systemd can read — it expands nothing itself.
describe('the nvm directory', () => {
  const pathLine = (content: string): string => line(content, 'Environment=PATH=');

  it('expands a bare ~ to the home directory', async () => {
    await boot({ config: config({ nvmDir: '~' }) });

    expect(pathLine(unit('api.service'))).toBe(
      'Environment=PATH=/home/tester/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin'
    );
  });

  it('expands a leading ~/ and keeps the rest of the path', async () => {
    await boot();

    expect(pathLine(unit('api.service'))).toBe(
      'Environment=PATH=/home/tester/.nvm/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin'
    );
  });

  it('leaves an absolute nvm directory alone', async () => {
    await boot({ config: config({ nvmDir: '/opt/nvm' }) });

    expect(pathLine(unit('api.service'))).toBe(
      'Environment=PATH=/opt/nvm/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin'
    );
  });
});

describe('a monitored service unit', () => {
  it('carries the banner, the group title and the target it is part of', async () => {
    await boot();

    const content = unit('api.service');

    expect(content.startsWith(BANNER)).toBe(true);
    expect(content).toContain('Description=API (Core) — The API service');
    expect(content).toContain(`Documentation=file://${path.join(workspaceRoot, 'BEs/dev/api')}`);
    expect(content).toContain('PartOf=marketplace.target');
    expect(content).toContain(`WorkingDirectory=${path.join(workspaceRoot, 'BEs/dev/api')}`);
    expect(content).toContain('SyslogIdentifier=api');
  });

  // Without [Install] `systemctl --user enable` refuses the unit outright, which is what makes
  // "never starts at boot" structural. An [Install] section here would make it a convention.
  // Read line by line, never as a substring: the file explains the absence in a comment that
  // spells the word, so `not.toContain` on the whole text fails on the explanation.
  it('has no [Install] section and cannot be enabled', async () => {
    await boot();

    expect(unit('api.service').split('\n')).not.toContain('[Install]');
  });

  // Restart=no and the three SuccessExitStatus spellings are one mechanism: a stop must read
  // clean and a crash must read 'failed', because the page tells them apart by exactly that.
  it('stays failed when it crashes and clean when it is stopped', async () => {
    await boot();

    const content = unit('api.service');

    expect(content).toContain('Restart=no');
    expect(content).toContain('KillMode=control-group');
    expect(content).toContain('SuccessExitStatus=143 15 SIGTERM');
  });
});

describe('the ExecStart command', () => {
  const execLine = (content: string): string => line(content, 'ExecStart=');

  // `exec` is the load-bearing word: it replaces the shell, so vite or tsx becomes the unit's
  // MainPID and takes SIGTERM directly. Without it systemd signals /bin/sh and the real process
  // is orphaned. Everything before the last segment stays ahead of it and still fails the unit.
  it('execs the last segment and leaves the ones before it in front', async () => {
    await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'tsc --noEmit && vite dev' } } } });

    const content = unit('api.service');

    expect(execLine(content)).toBe("ExecStart=/bin/sh -c 'tsc --noEmit && exec vite dev'");
    expect(content).toContain(
      '# from BEs/dev/api/package.json scripts.dev: tsc --noEmit && vite dev'
    );
  });

  it('resolves a bare binary against the repo node_modules/.bin when it is there', async () => {
    await boot({ bins: [repoBin('BEs/dev/api', 'vite')] });

    expect(execLine(unit('api.service'))).toBe(
      `ExecStart=/bin/sh -c 'exec ${repoBin('BEs/dev/api', 'vite')}'`
    );
  });

  // The unit PATH carries the pinned node and nothing repo-local, so a name that is not there is
  // left as written rather than rewritten into a path that does not exist.
  it('leaves a command alone when the repo has no such local binary', async () => {
    await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'node server.js' } } } });

    expect(execLine(unit('api.service'))).toBe("ExecStart=/bin/sh -c 'exec node server.js'");
  });

  // npx would re-resolve the binary the line above just resolved, and put another process between
  // systemd and the target.
  it('drops a leading npx and resolves what it was going to run', async () => {
    await boot({
      packages: { 'BEs/dev/api': { scripts: { dev: 'npx vite --host' } } },
      bins: [repoBin('BEs/dev/api', 'vite')]
    });

    expect(execLine(unit('api.service'))).toBe(
      `ExecStart=/bin/sh -c 'exec ${repoBin('BEs/dev/api', 'vite')} --host'`
    );
  });

  it('drops an empty segment left by a trailing &&', async () => {
    await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'tsc && ' } } } });

    expect(execLine(unit('api.service'))).toBe("ExecStart=/bin/sh -c 'exec tsc'");
  });

  // A segment is split on whitespace to find its binary (parts[0]) and rejoined with a single
  // space. Splitting on a run of whitespace as one delimiter, rather than one whitespace character
  // at a time, is what stops a double space (or a stray tab) from leaving an empty '' element that
  // rejoining would turn back into extra, meaningless whitespace in the final command.
  it('collapses a run of whitespace inside a segment to one space', async () => {
    await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'vite  --host' } } } });

    expect(execLine(unit('api.service'))).toBe("ExecStart=/bin/sh -c 'exec vite --host'");
  });
});

describe('the scripts it refuses to translate', () => {
  it('names the script and the file when the repo does not define it', async () => {
    await expect(boot({ packages: { 'BEs/dev/api': { scripts: { start: 'vite' } } } })).rejects
      .toThrow(
        `api: no "dev" script in ${path.join(workspaceRoot, 'BEs/dev/api', 'package.json')}. ` +
          'services.json names a script that repo does not define.'
      );
  });

  it('says the same when the repo has no package.json at all', async () => {
    await expect(boot({ packages: {} })).rejects.toThrow('api: no "dev" script in');
  });

  it('says the same when the package.json has no scripts block', async () => {
    await expect(boot({ packages: { 'BEs/dev/api': { name: 'api' } } })).rejects.toThrow(
      'api: no "dev" script in'
    );
  });

  // Guessing at a shell construct this generator does not parse would produce a unit that runs
  // something other than what the repo's script says, and nothing downstream would notice — so the
  // message has to say that, in full, not just name the script. `.rejects.toThrow(string)` only
  // checks a substring, which would still pass with the explanation blanked out, so the exact
  // message is asserted directly off the caught error instead.
  it('refuses shell syntax it does not parse, quoting the script back and explaining why', async () => {
    let caught: unknown;

    try {
      await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'vite || true' } } } });
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(Error);
    expect((caught as Error).message).toBe(
      'api: the "dev" script uses shell syntax this generator does not parse ("vite || true"). ' +
        'Simplify the script, or teach buildExecCommand about it — guessing here would silently ' +
        'produce a unit that runs the wrong thing.'
    );
  });

  // ⚠️ The guard masks `&&` before testing for a bare `&`, and this is the case that says so: an
  // unmasked test matches the second `&` of every `&&` and rejects every chained script there is.
  it('does not mistake the && it handles for the & it refuses', async () => {
    await boot({ packages: { 'BEs/dev/api': { scripts: { dev: 'tsc && vite' } } } });

    expect(unit('api.service')).toContain("ExecStart=/bin/sh -c 'tsc && exec vite'");
  });
});

describe('the target unit', () => {
  // Wants= starts them together; each unit's own PartOf= is what propagates a stop back down.
  it('wants and orders after every unit it groups', async () => {
    await boot({ config: TWO_GROUPS, packages: TWO_GROUPS_PACKAGES });

    const content = unit('marketplace.target');

    expect(content.startsWith(BANNER)).toBe(true);
    expect(content).toContain('Description=Marketplace platform — all 3 monitored dev services');
    expect(content.split('\n').filter((l) => l.startsWith('Wants='))).toStrictEqual([
      'Wants=api.service',
      'Wants=web.service',
      'Wants=gw.service'
    ]);
    expect(content.split('\n').filter((l) => l.startsWith('After='))).toStrictEqual([
      'After=api.service',
      'After=web.service',
      'After=gw.service'
    ]);
  });

  it('has no [Install] section either', async () => {
    await boot();

    expect(unit('marketplace.target').split('\n')).not.toContain('[Install]');
  });
});

describe('the monitor unit', () => {
  // The one generated unit that may be enabled: nothing else can start the control page, and the
  // page is how anything else gets started. Enabling it enables none of the units it monitors.
  it('is the only one with an [Install] section, and restarts itself', async () => {
    await boot();

    const content = unit('marketplace-status.service');

    expect(content).toContain('[Install]\nWantedBy=default.target');
    expect(content).toContain('Restart=on-failure');
    expect(content).toContain('RestartSec=2');
    expect(content).toContain('Environment=NODE_ENV=production');
    expect(content).toContain(`WorkingDirectory=${repoDir}`);
    expect(content).toContain('SyslogIdentifier=marketplace-status');
  });

  it('takes its own command from its own package.json, exec and all', async () => {
    await boot({
      monitor: { scripts: { start: 'tsc && node dist/server.js' } },
      bins: [ownBin('tsc')]
    });

    const content = unit('marketplace-status.service');

    expect(line(content, 'ExecStart=')).toBe(
      `ExecStart=/bin/sh -c '${ownBin('tsc')} && exec node dist/server.js'`
    );
    expect(content).toContain(
      '# from marketplace-services-status/package.json scripts.start: tsc && node dist/server.js'
    );
  });

  // The monitor unit is built through the same buildExecCommand() as every other unit, passed a
  // synthetic { id: 'marketplace-status', script: 'start' } rather than a services.json entry. If
  // this repo's own package.json ever lost its start script, the error has to name it by that id —
  // an id no services.json service ever carries — not by some other repo's id.
  it("names itself 'marketplace-status', not a service id, when its own start script is missing", async () => {
    await expect(boot({ monitor: { scripts: {} } })).rejects.toThrow(
      `marketplace-status: no "start" script in ${path.join(repoDir, 'package.json')}.`
    );
  });
});
