#!/usr/bin/env bash
#
# Move the shared keys out of sixteen real environment files and into one (ADR-053).
#
# ⚠️ YOU RUN THIS, NOT AN ASSISTANT. It is the only script in this workspace that reads values out
# of a real `.env` and writes them somewhere else. It prints VARIABLE NAMES ONLY — never a value,
# never a whole line, not even in a diff — and that is the whole reason it exists as a script rather
# than as a sequence of edits somebody performs by hand with the files open.
#
#   ./scripts/env-shared-migrate.sh seed            # build .env.shared from what the repos already have
#   ./scripts/env-shared-migrate.sh strip           # show which lines WOULD be removed  (dry run)
#   ./scripts/env-shared-migrate.sh strip --apply   # remove them, leaving a .env.bak beside each file
#
# Run them in that order, and read the seed report before stripping.
#
# ── seed ─────────────────────────────────────────────────────────────────────
# Takes the key NAMES from the committed `env.shared` template, collects each one's value from every
# repo's `.env`, and writes `.env.shared` — but only for a key whose value is IDENTICAL everywhere it
# appears. A key the repos disagree on is left out and reported by name with the count, because
# guessing which repo is right is exactly the R04 failure this layer exists to prevent, and the
# shared layer cannot be overridden: a wrong value seeded here is a wrong value in fifteen repos at
# once. Resolve the disagreement in the repos first, then seed again.
#
# ── strip ────────────────────────────────────────────────────────────────────
# Removes, from each repo's `.env`, the assignment lines for keys `.env.shared` actually answers —
# present AND non-empty, the same rule `.envrc` applies when it unsets the blanks. It refuses to
# strip a key whose repo value differs from the shared one, by name, because that repo would silently
# start using a different server the moment the line went away.
#
# ⚠️ The committed `env` templates are NEVER touched. They document what a service reads, which is a
# different question from where the value comes from, and a service's own template is the only place
# the first question has a complete answer. `./scripts/env-diff.sh` reports a stripped key as SHARED.
#
# Exit status is 0 unless the arguments are wrong or a write fails.

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

TEMPLATE=env.shared
TARGET=.env.shared

PROJECTS=(BEs/dev/*/ BEs/marketplace-common BEs/marketplace-db-setup marketplace-services-status marketplace-admin marketplace-shopowner marketplace-user marketplace-docker-DBs)

# ⚠️ `tr -d ' \t'`, never `tr -d '[:space:]'` — that class contains the newline and returns every key
# concatenated into a single word. `scripts/env-diff.sh` carried that bug for months.
key_names() { grep -oE '^[[:space:]]*[A-Za-z_][A-Za-z_0-9]*[[:space:]]*=' "$1" | tr -d ' \t=' | sort -u; }

# Raw text after the FIRST `=` of the first assignment of $2 in file $1. Never printed by this script.
value_of() { sed -nE "s/^[[:space:]]*$2[[:space:]]*=//p" "$1" | head -n 1; }

has_key() { grep -qE "^[[:space:]]*$2[[:space:]]*=" "$1"; }

usage() {
	printf 'usage: %s seed [--force] | strip [--apply]\n' "$0" >&2
	exit 2
}

[ "$#" -ge 1 ] || usage
cmd=$1
shift

case "$cmd" in
seed)
	force=0
	[ "${1:-}" = "--force" ] && force=1

	[ -f "$TEMPLATE" ] || {
		printf 'no %s in this directory — run this from anywhere, it cd-s to the workspace root itself\n' "$TEMPLATE" >&2
		exit 1
	}

	if [ -f "$TARGET" ] && [ "$force" -eq 0 ]; then
		printf '%s already exists. Move it aside, or re-run with --force to overwrite it.\n' "$TARGET" >&2
		exit 1
	fi

	tmp=$(mktemp) && trap 'rm -f "$tmp"' EXIT

	{
		printf '# Generated by scripts/env-shared-migrate.sh seed — see env.shared for what each key is.\n'
		printf '# Every value below was already identical in every repo that carries the key.\n\n'
	} >"$tmp"

	seeded=() skipped=() nowhere=()

	while read -r key; do
		[ -n "$key" ] || continue

		distinct=$(
			for dir in "${PROJECTS[@]}"; do
				real="${dir%/}/.env"
				[ -f "$real" ] || continue
				has_key "$real" "$key" || continue
				value_of "$real" "$key"
			done | grep -v '^[[:space:]]*$' | sort -u
		)

		count=$(printf '%s' "$distinct" | grep -c . )

		case "$count" in
		0)
			nowhere+=("$key")
			printf '%s=\n' "$key" >>"$tmp"
			;;
		1)
			seeded+=("$key")
			printf '%s=%s\n' "$key" "$distinct" >>"$tmp"
			;;
		*)
			skipped+=("$key $count")
			printf '# %s — omitted: %s different values across the repos, resolve them first\n' "$key" "$count" >>"$tmp"
			;;
		esac
	done < <(key_names "$TEMPLATE")

	mv "$tmp" "$TARGET" && chmod 600 "$TARGET"
	trap - EXIT

	printf 'wrote %s (mode 600)\n\n' "$TARGET"
	[ "${#seeded[@]}" -gt 0 ] && printf '  SEEDED    %s\n' "${seeded[*]}"
	[ "${#nowhere[@]}" -gt 0 ] && printf '  NO VALUE  %s\n            left empty, therefore inert — .envrc unsets these and each repo keeps its own\n' "${nowhere[*]}"
	if [ "${#skipped[@]}" -gt 0 ]; then
		printf '\n  ⚠️ DISAGREE — omitted, one line each as "<key> <how many distinct values>":\n'
		printf '     %s\n' "${skipped[@]}"
		printf '     The shared layer cannot be overridden, so a guess here is wrong in every repo at\n'
		printf '     once. Make the repos agree, then re-run with --force.\n'
	fi
	printf '\nNext: check it, then `cp envrc .envrc && direnv allow`, then `%s strip`.\n' "$0"
	;;

strip)
	apply=0
	[ "${1:-}" = "--apply" ] && apply=1

	[ -f "$TARGET" ] || {
		printf 'no %s yet — run `%s seed` first\n' "$TARGET" "$0" >&2
		exit 1
	}

	# Only the keys the layer actually answers: present AND non-empty, the rule .envrc applies.
	mapfile -t SHARED < <(grep -E '^[[:space:]]*[A-Za-z_][A-Za-z_0-9]*[[:space:]]*=[[:space:]]*[^[:space:]]' "$TARGET" |
		grep -oE '^[[:space:]]*[A-Za-z_][A-Za-z_0-9]*' | tr -d ' \t' | sort -u)

	[ "${#SHARED[@]}" -gt 0 ] || {
		printf '%s answers no key — nothing to strip\n' "$TARGET" >&2
		exit 1
	}

	[ "$apply" -eq 1 ] || printf 'DRY RUN — nothing is written. Re-run with --apply.\n\n'

	for dir in "${PROJECTS[@]}"; do
		dir=${dir%/}
		real="$dir/.env"
		[ -f "$real" ] || continue

		remove=() conflict=()

		for key in "${SHARED[@]}"; do
			has_key "$real" "$key" || continue

			if [ "$(value_of "$real" "$key")" = "$(value_of "$TARGET" "$key")" ]; then
				remove+=("$key")
			else
				conflict+=("$key")
			fi
		done

		[ "${#remove[@]}" -eq 0 ] && [ "${#conflict[@]}" -eq 0 ] && continue

		printf '%s\n' "$dir"
		[ "${#remove[@]}" -gt 0 ] && printf '  REMOVE    %s\n' "${remove[*]}"
		if [ "${#conflict[@]}" -gt 0 ]; then
			printf '  ⚠️ KEPT   %s\n' "${conflict[*]}"
			printf '            this repo disagrees with the shared value. Removing the line would\n'
			printf '            silently repoint it — decide which is right before stripping these.\n'
		fi

		if [ "$apply" -eq 1 ] && [ "${#remove[@]}" -gt 0 ]; then
			cp -p "$real" "$real.bak" || exit 1

			for key in "${remove[@]}"; do
				sed -i -E "/^[[:space:]]*$key[[:space:]]*=/d" "$real" || exit 1
			done

			printf '  written, previous file kept as %s.bak\n' "$real"
		fi

		printf '\n'
	done

	[ "$apply" -eq 1 ] && printf 'Now: ./scripts/env-diff.sh — every removed key should read SHARED, none MISSING.\n'
	;;

*) usage ;;
esac
